[theme]
# Primary accent color for interactive elements.
primaryColor = "#cbc5c5"

# Background color for the main content area.
backgroundColor = "#86a3bd"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#4CAF50"

# Color used for almost all text.
textColor = "#454545"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"